# Generated by Django 3.2.8 on 2022-01-23 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ra", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="bookmark",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="ra.bookmark_detail",
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="ra.group",
            ),
        ),
    ]
