# Generated by Django 3.2.6 on 2021-11-21 16:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0003_auto_20211120_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='member',
        ),
        migrations.AlterField(
            model_name='bookmark_folder',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 0, 47, 17, 241777)),
        ),
        migrations.AlterField(
            model_name='folder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 0, 47, 17, 241777)),
        ),
        migrations.AlterField(
            model_name='group',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 0, 47, 17, 239777)),
        ),
        migrations.AlterField(
            model_name='group_bookmark',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 0, 47, 17, 240777)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 0, 47, 17, 243777)),
        ),
        migrations.AlterField(
            model_name='site',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 0, 47, 17, 241777)),
        ),
        migrations.AlterField(
            model_name='user_access',
            name='date_of_access',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 0, 47, 17, 242777)),
        ),
        migrations.AlterField(
            model_name='user_bookmark',
            name='dateAccessed',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 0, 47, 17, 237778)),
        ),
        migrations.AlterField(
            model_name='user_bookmark',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 0, 47, 17, 237778)),
        ),
        migrations.CreateModel(
            name='Group_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ra.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Group_member',
            },
        ),
    ]
