# Generated by Django 3.2.6 on 2021-11-22 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0005_auto_20211122_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark_folder',
            name='date_removed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group_bookmark',
            name='date_removed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_bookmark',
            name='date_removed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark_folder',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 21, 36, 27, 588799)),
        ),
        migrations.AlterField(
            model_name='folder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 21, 36, 27, 587798)),
        ),
        migrations.AlterField(
            model_name='group',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 21, 36, 27, 586799)),
        ),
        migrations.AlterField(
            model_name='group_bookmark',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 21, 36, 27, 587798)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 21, 36, 27, 590798)),
        ),
        migrations.AlterField(
            model_name='site',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 21, 36, 27, 588799)),
        ),
        migrations.AlterField(
            model_name='user_access',
            name='date_of_access',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 21, 36, 27, 589798)),
        ),
        migrations.AlterField(
            model_name='user_bookmark',
            name='dateAccessed',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 21, 36, 27, 584803)),
        ),
        migrations.AlterField(
            model_name='user_bookmark',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 21, 36, 27, 584803)),
        ),
    ]
